### ISSUE TITLE
Livewire Uncaught (in promise) ReferenceError: L is not defined

### ISSUE THREAD

**Issue by wazimshizm** [LarsWiegers/laravel-maps#16]
When including the component inside a livewire component with an @if tag, the component throws a Uncaught (in promise) ReferenceError: L is not defined in the console and fails to render the rest of the page.

It works inside the livewire component if not inside an @if tag. 

I'm guessing this has to do with the order the scripts are loaded? Any help would be hugely appreciated. Thanks!

**Comment by LarsWiegers** [comment]
Hi! Thx for creating an issue.

I have not yet tried to do any livewire things with this package. 

Maybe livewire does not like the script tag that is included in the component?

what you could do is instead of 
`
@if(someCondition)
<x-maps-leaflet></x-maps-leaflet>
@endif
`

do this:
`
<x-maps-leaflet class="@if(someCondition) display-none @endif"></x-maps-leaflet>
`

A test repository would help identifying what is going wrong.
Do you know how to set that up?

**Comment by wazimshizm** [comment]
The issue was fixed by including the 
```
<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"...
```
**_after_** the livewire scripts at the bottom of the page. It must be to do with the order they are loaded.

**Comment by LarsWiegers** [comment]
Cool, thx for getting back and posting your solution. 

In the future we might include a default livewire component.

Closing the issue for now.
